# Generated by Django 6.0.4 on 2026-05-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('company', models.CharField(max_length=200, verbose_name='Организация')),
                ('location', models.CharField(max_length=150, verbose_name='Город / Регион')),
                ('employment_type', models.CharField(choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('intern', 'Стажировка'), ('remote', 'Удалённая работа')], default='full', max_length=20, verbose_name='Тип занятости')),
                ('experience', models.CharField(choices=[('none', 'Без опыта'), ('1year', 'До 1 года'), ('3years', 'От 1 до 3 лет'), ('5years', 'От 3 до 5 лет')], default='none', max_length=20, verbose_name='Опыт работы')),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата от (сом)')),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата до (сом)')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Обязанности')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Контактный телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
