# Generated by Django 6.0.5 on 2026-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
