# Generated by Django 6.0.5 on 2026-05-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон отправителя'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='check_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_checks/', verbose_name='Чек'),
        ),
    ]
