# Generated by Django 6.0.5 on 2026-06-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment_comment_payment_sender_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дата платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_time',
            field=models.CharField(blank=True, max_length=10, verbose_name='Время платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_bank',
            field=models.CharField(blank=True, max_length=100, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя отправителя'),
        ),
    ]
