# Generated by Django 6.0.6 on 2026-06-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment_payment_date_payment_payment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_time',
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender_bank',
            field=models.CharField(blank=True, choices=[('mbank', 'M-Bank'), ('obank', 'O!Bank'), ('optima', 'Optima Bank'), ('bakai', 'Бакай Банк'), ('demir', 'Демир Банк'), ('kompanion', 'Компаньон Банк'), ('aiyl', 'Айыл Банк'), ('kicb', 'KICB'), ('rsk', 'РСК Банк'), ('dos', 'Дос-Кредобанк'), ('elqr', 'ELQR'), ('other', 'Другой')], max_length=50, verbose_name='Банк'),
        ),
    ]
